package_assets: on
compress_assets: on
# note: don't use yui compression, it broke the combined javascript for some reason
javascript_compressor: closure
embed_assets: on

javascripts:
  main:
    - public/javascripts/UIHandler.js
    - public/javascripts/LoginsController.js
    - public/javascripts/RatingsController.js
    - public/javascripts/application.js
    - public/javascripts/global.js
    - public/javascripts/classicly-autocomplete.js
    - public/javascripts/jquery.rating.js
    - public/javascripts/rails.js
    - public/javascripts/notifications.js
    - public/javascripts/jquery.lazyload.min.js
stylesheets:
  common:
    - public/stylesheets/compiled/screen.css
    # NOTE: SASS chokes on it if I try to make it a partial :(
    - public/stylesheets/bootstrap-1.1.1.min.css
    - public/stylesheets/jquery.rating.css
    - public/stylesheets/notifications.css
  terms_of_service:
    - public/stylesheets/compiled/terms_of_service.css

