embed_assets: on
javascript_compressor: yui

javascripts:
  jquery:
    - public/javascripts/jquery.js
  main: 
    - public/javascripts/jquery.js
    - public/javascripts/jquery.metadata.js
    - public/javascripts/covers.js
    - public/javascripts/global.js
    - public/javascripts/application.js
    - public/javascripts/jqueryui.js
    - public/javascripts/rails.js
    - public/javascripts/jquery.rating.js
    - public/javascripts/masonry.js
  main_without_jquery_nor_jquery_ui:
    - public/javascripts/jquery.metadata.js
    - public/javascripts/global.js
    - public/javascripts/application.js
    - public/javascripts/rails.js
    - public/javascripts/jquery.rating.js
    - public/javascripts/covers.js
  collections:
    - public/javascripts/collection-page.js

stylesheets:
  common:
    - public/stylesheets/main.css
    - public/stylesheets/grid.css
  blog:
    - public/stylesheets/blog.css
  jqueryui:
    - public/stylesheets/jqueryui.css
  rating:
    - public/stylesheets/jquery.rating.css
