embed_assets: on
javascript_compressor: yui
package_assets: always

javascripts:
  main: 
    - public/javascripts/jquery.js
    - public/javascripts/jquery.metadata.js
    - public/javascripts/application.js
    - public/javascripts/jqueryui.js
    - public/javascripts/rails.js
    - public/javascripts/jquery.rating.js

stylesheets:
  common:
    - public/stylesheets/main.css
    - public/stylesheets/grid.css
  jqueryui:
    - public/stylesheets/jqueryui.css
  rating:
    - public/stylesheets/jquery.rating.css
