package_assets: on
compress_assets: on
# note: don't use yui compression, it broke the combined javascript for some reason
javascript_compressor: closure
embed_assets: on

javascripts:
  main:
    - public/javascripts/application.js
    - public/javascripts/rails.js
    - public/javascripts/jquery.rating.js
    - public/javascripts/global.js
stylesheets:
  common:
    - public/stylesheets/compiled/screen.css
