require 'acceptance/acceptance_helper'

feature 'Crud posts feature: ', %q{
  In order to make my website more interesting
  As an admin
  I want to be able to create, update and delete  blog posts
} do

  background do
    # Given I am an admin user
    @admin = AdminUser.make!
    # And I log in
    admin_login(@admin)
  end
  
  scenario 'creating a post' do
    text = %q{
      You love to read great works of literature, but sometimes you just can't settle on a book to read. 
      One great place to find free books to read online is with a list of the 20th century's greatest works of fiction!In 1998, 
      The Modern Library published its famous "100 Best" list, a collection of the crowning achievements of English language 
      fiction from the last century. This list was generated by a poll of more than 400,000 avid readers. Of the 100 "Best" books, 
      27 are free books to read online using a built-in reader, or are free to download for your iPad, Kindle, or Sony tablet. 
    }
    create_blog_post_with_text text
    # Then I should be on the edit page for this post
    page.should have_content('Edit this blog post')
    find(:xpath, "id('blog_post_title')").value.should == 'The Blog Post'
  end
  
  scenario 'Creating a blog post with a break tag to determine the amount of text to show on the frontend' do
    # And given I have created a blog_post with a break tag
    title = 'Excellent blog post'
    text =  "<p>You love to read great works of literature, but sometimes you just can't settle on a book to read.</p><p>Hello World!</p>
            <br/> This does not have to appear!"
    create_blog_post_with_text text, title
    # When I go to the blog page
    visit blog_path

    within(:xpath, "//div[@class='show-post']//div[@class='blog-title']//h2//a[text()='#{title}']") do    
      find(:xpath, "..//..//..//div[@class='content']").text.should include("Hello World!")
      find(:xpath, "..//..//..//div[@class='content']").text.should include("You love to read great works of literature, but sometimes you just can't settle on a book to read.")
      find(:xpath, "..//..//..//div[@class='content']").text.should_not include('This does not have to appear!')
    end
  end
end
